### ISSUE TITLE
Kanban_Capstone

### ISSUE THREAD

**Issue by vanina123** [vanina123/Kanban_Capstone#21]
Below is the GitHub Project
https://github.com/vanina123/Kanban_Capstone/projects/2

- We are two members in our group(@vanina123, @Adams-Ghub)

**Comment by omarsalem7** [comment]
Hi @vanina123, @Adams-Ghub 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- Kanban cards created properly with good descriptions ✔️

## Required Changes ♻️
- [ ] Kindly consider assign tasks between each team members equally like the example below
>![image](https://user-images.githubusercontent.com/53402600/234096424-bd63cb0f-5a7a-4d91-b8ce-31d6f8d737e1.png)

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @vanina123, and @Adams-Ghub👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
